### ISSUE TITLE
Minify rewrite CSS assets to the wrong location when using themes

### ISSUE THREAD

**Issue by hellodaniel** [maurymmarques/minify-cakephp#20]
When using themes Minify seems to reliably rewrite assets to the wrong location. 

e.g.: /app/webroot/theme/ThemeName/css/styles.css

	.icon {
	    background-image: url("../images/icons.png");
	}
	
Gets re-written to: 
	
	background-image: url(/images/icons.png);
	
...and of course breaks ALL the linked assets. 

The only solution I have at the minute is to not use relative paths (and re-write all of the plug-ins to do the same). 

i.e.: If I edit all the CSS docs to use this format it works (but is a pain to do across all sites / plugins / etc) -- 
	
	.icon {
	    background-image: url("/theme/MyTheme/images/icons.png");
	}
	

I'm sure this was working in the past and the only reason I flag it as an issue is that it now reliably fails on all sites I've used Minify-CakePHP (not just one instance). 

**An simple example** (i'll need to fix this soon):

Minified: http://optibuild.arcadedigital.com.au/min-css?f=theme/Optibuild/css/bootstrap-checkbox.css

Unminified: 
http://optibuild.arcadedigital.com.au/theme/Optibuild/css/bootstrap-checkbox.css

**Comment by michapixel** [comment]
edit app\Plugin\Minify\Vendor\minify\lib\Minify\Controller\Base.php

line 50 where the default options are set:

,'rewriteCssUris' => true

change this to false.

Done.

**Comment by ynaderi** [comment]
Does not work for me
