### ISSUE TITLE
MinifyHelper::assetUrl function is undefined

### ISSUE THREAD

**Issue by charanjeet2008** [maurymmarques/minify-cakephp#21]
I am getting below error in this branch.
![screenshot from 2015-01-13 12 34 31](https://cloud.githubusercontent.com/assets/4629941/5717107/bfad90ba-9b20-11e4-8921-36162bfeef42.png)

Method MinifyHelper::assetUrl does not exist.

**Comment by maurymmarques** [comment]
What is your version of CakePHP? 
Did you follow all the plugin installation steps?
