### ISSUE TITLE
Minify not working properly

### ISSUE THREAD

**Issue by kunokdev** [maurymmarques/minify-cakephp#25]
### If this is set like:
`Configure::write('MinifyAsset', false);`
### And if it is set like:
`Configure::write('MinifyAsset', true);`### 
### then file looks like this: (it's a css file)
`<pre class="cake-error"><a href="javascript:void(0);" onclick="document.getElementById('cakeErr576bddaa9c047-trace').style.display = (document.getElementById('cakeErr576bddaa9c047-trace').style.display == 'none' ? '' : 'none');"><b>Warning</b> (2)</a>: fopen(/var/www/html/tmc/app/tmp/cache/minify/minify_styles.css_29ce0e75607d5367c39bf73c33fb936e): failed to open stream: No such file or directory [<b>APP/Plugin/Minify/Vendor/minify/lib/Minify/Cache/File.php</b>, line <b>100</b>]<div id="cakeErr576bddaa9c047-trace" class="cake-stack-trace" style="display: none;"><a href="javascript:void(0);" onclick="document.getElementById('cakeErr576bddaa9c047-code').style.display = (document.getElementById('cakeErr576bddaa9c047-code').style.display == 'none' ? '' : 'none')">Code</a> <a href="javascript:void(0);" onclick="document.getElementById('cakeErr576bddaa9c047-context').style.display = (document.getElementById('cakeErr576bddaa9c047-context').style.display == 'none' ? '' : 'none')">Context</a><pre id="cakeErr576bddaa9c047-code" class="cake-code-dump" style="display: none;"><code><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">{</span></span></code>
<code><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="color: #007700">if&nbsp;(</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">_locking</span><span style="color: #007700">)&nbsp;{</span></span></code>
<span class="code-highlight"><code><span style="color: #000000"><span style="color: #0000BB">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$fp&nbsp;</span><span style="color: #007700">=&nbsp;</span><span style="color: #0000BB">fopen</span><span style="color: #007700">(</span><span style="color: #0000BB">$this</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">_path&nbsp;</span><span style="color: #007700">.&nbsp;</span><span style="color: #DD0000">'/'&nbsp;</span><span style="color: #007700">.&nbsp;</span><span style="color: #0000BB">$id</span><span style="color: #007700">,&nbsp;</span><span style="color: #DD0000">'rb'</span><span style="color: #007700">);</span></span></code></span></pre><pre id="cakeErr576bddaa9c047-context" class="cake-context" style="display: none;">$id = &#039;minify_styles.css_29ce0e75607d5367c39bf73c33fb936e&#039;</pre><pre class="stack-trace">fopen - [internal], line ??
Minify_Cache_File::fetch() - APP/Plugin/Minify/Vendor/minify/lib/Minify/Cache/File.php, line 100
Minify_Cache_File::store() - APP/Plugin/Minify/Vendor/minify/lib/Minify/Cache/File.php, line 37
Minify::serve() - APP/Plugin/Minify/Vendor/minify/lib/Minify.php, line 292
include - APP/Plugin/Minify/Vendor/minify/index.php, line 64
App::_loadVendor() - CORE/Cake/Core/App.php, line 763
App::import() - CORE/Cake/Core/App.php, line 651
MinifyController::index() - APP/Plugin/Minify/Controller/MinifyController.php, line 19`
...

**Comment by maurymmarques** [comment]
It seems something with permission.
Did you create a folder called "minify" in app/tmp/cache and give it permission to **read** and **write**?

**Comment by kunokdev** [comment]
Yes it was related to permissions, they break when you pull code on Linux machine from Windows machine.
